# cloud-build for dev environment
steps:
  - name: gcr.io/cloud-builders/npm
    env:
    # to suppress logging during install
    - 'CI=true'
    args: ['install']
    # volumes:
    #   - name: 'ssh'
    #     path: /root/.ssh
  - name: gcr.io/cloud-builders/npm
    args: ['run', 'clean']
  - name: gcr.io/cloud-builders/npm
    args: [
      'run',
      'build',
      '--',
      '--project=client',
      '--prod',
      '-c=dev'
    ]
  - name: gcr.io/cloud-builders/npm
    args: [
      'run',
      'build',
      '--',
      '--project=api',
      '--prod',
      '-c=dev'
    ]
  - name: ubuntu
    args: [
      'cp',
      'apps/api/environemnts/app.dev.yaml',
      'dist/apps/api/app.yaml'
    ]
  # TODO: add tests here
  - name: gcr.io/cloud-builders/gcloud
    dir: 'dist'
    args: ['app', 'deploy', 'dist/apps/api/app.yml']
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', 'dist/apps/client', 'gs://client-host-dev']
